
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action FileAction1;

	private global::Gtk.Action ClearAction;

	private global::Gtk.Action QuitAction;

	private global::Gtk.Action newAction;

	private global::Gtk.Action refreshAction;

	private global::Gtk.Action executeAction;

	private global::Gtk.Action deleteAction;

	private global::Gtk.HBox hbox4;

	private global::Gtk.VBox vbox4;

	private global::Gtk.MenuBar menubar3;

	private global::Gtk.VBox vb;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.HPaned hpaned2;

	private global::Gtk.HBox hbox5;

	private global::Gtk.VBox vbGl;

	private global::Gtk.VBox vbox1;

	private global::Gtk.Notebook notebook2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TreeView treeview;

	private global::Gtk.Label label3;

	private global::Gtk.Statusbar statusbar;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("&File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("&File");
		w1.Add (this.FileAction, null);
		this.FileAction1 = new global::Gtk.Action ("FileAction1", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction1, null);
		this.ClearAction = new global::Gtk.Action ("ClearAction", global::Mono.Unix.Catalog.GetString ("_Clear"), null, null);
		this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Clear");
		w1.Add (this.ClearAction, "<Alt><Mod2>c");
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quit");
		w1.Add (this.QuitAction, "<Control><Mod2>q");
		this.newAction = new global::Gtk.Action ("newAction", null, null, "gtk-new");
		w1.Add (this.newAction, null);
		this.refreshAction = new global::Gtk.Action ("refreshAction", null, null, "gtk-refresh");
		w1.Add (this.refreshAction, null);
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.deleteAction = new global::Gtk.Action ("deleteAction", null, null, "gtk-delete");
		w1.Add (this.deleteAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar3'><menu name='FileAction1' action='FileAction1'><menuitem name='ClearAction' action='ClearAction'/><separator/><menuitem name='QuitAction' action='QuitAction'/></menu></menubar></ui>");
		this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
		this.menubar3.Name = "menubar3";
		this.vbox4.Add (this.menubar3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.menubar3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.vb = new global::Gtk.VBox ();
		this.vb.Name = "vb";
		this.vb.Spacing = 6;
		// Container child vb.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='newAction' action='newAction'/><toolitem name='refreshAction' action='refreshAction'/><toolitem name='executeAction' action='executeAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vb.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vb[this.toolbar1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox4.Add (this.vb);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vb]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hpaned2 = new global::Gtk.HPaned ();
		this.hpaned2.CanFocus = true;
		this.hpaned2.Name = "hpaned2";
		this.hpaned2.Position = 648;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Events = ((global::Gdk.EventMask)(4));
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.vbGl = new global::Gtk.VBox ();
		this.vbGl.CanDefault = true;
		this.vbGl.CanFocus = true;
		this.vbGl.Events = ((global::Gdk.EventMask)(4));
		this.vbGl.Name = "vbGl";
		this.vbGl.Spacing = 6;
		this.hbox5.Add (this.vbGl);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbGl]));
		w5.Position = 0;
		this.hpaned2.Add (this.hbox5);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.hbox5]));
		w6.Resize = false;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.treeview = new global::Gtk.TreeView ();
		this.treeview.WidthRequest = 80;
		this.treeview.CanFocus = true;
		this.treeview.Name = "treeview";
		this.treeview.HeadersVisible = false;
		this.GtkScrolledWindow1.Add (this.treeview);
		this.notebook2.Add (this.GtkScrolledWindow1);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Objects");
		this.notebook2.SetTabLabel (this.GtkScrolledWindow1, this.label3);
		this.label3.ShowAll ();
		this.vbox1.Add (this.notebook2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook2]));
		w9.Position = 0;
		this.hpaned2.Add (this.vbox1);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.hpaned2[this.vbox1]));
		w10.Resize = false;
		this.vbox4.Add (this.hpaned2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hpaned2]));
		w11.Position = 2;
		// Container child vbox4.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.vbox4.Add (this.statusbar);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.statusbar]));
		w12.Position = 3;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox4.Add (this.vbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox4]));
		w13.Position = 0;
		this.Add (this.hbox4);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 818;
		this.DefaultHeight = 606;
		this.vbGl.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.QuitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.newAction.Activated += new global::System.EventHandler (this.OnNewActionActivated);
		this.refreshAction.Activated += new global::System.EventHandler (this.OnRefreshActionActivated);
		this.executeAction.Activated += new global::System.EventHandler (this.OnExecuteActionActivated);
	}
}
